platform:ios, '7.0'
pod "AFNetworking"
pod "AFNetworking-RACExtensions"
pod "AMSmoothAlert"
pod "ASProgressPopUpView"
pod "BlockAlertsAnd-ActionSheets" 
pod "GPUImage"
pod "JASidePanels"
pod "JSONModel"
pod "PMValidation"
pod "pop"
pod "ReactiveCocoa"
pod "ReactiveCoreData"
pod "ReactiveViewModel"
pod "SimpleSyncService"
pod "SLCoreDataStack"
pod 'SLRESTfulCoreData'
pod 'SLRESTfulCoreDataUI'
pod "UICKeyChainStore"
pod "UMengSocial"
pod "YLMoment"
#pod "ZBarSDK"
pod "ZXingObjC"

